### ISSUE TITLE
Give project directory to dynamic datafiles for relative file resolution

### ISSUE THREAD

**Issue by Raqbit** [BlameButton/docmaker#3]
**Issue**

Currently dynamic data files are executed from within the user's current working directory. This means that if you're reading files in this dynamic data file, you should do so relative to the place where the user runs the build command.

This behavior does not fit well with the rest of docmaker, which usually resolves things relative to the project directory.

---

**Example**:

```js
const fs = require("fs");
module.exports = {
  lorem: fs.readFileSync("lorem.txt"),
};
```

with the following directory structure:

```
.
├── build
│   ├── index.html
│   └── out.pdf
├── chapters
│   ├── 1-foobar.md
│   └── 2-johndoe.md
├── docmaker.yaml
├── lorem_data.js
└── lorem.txt
```

The `readFileSync` call will throw if we're not in the same directory as `lorem.txt`. For instance, when we are in `chapters`, `docmaker` will resolve everything fine but the `lorem_data.js` dynamic data file will fail to resolve lorem.txt

---

**Proposed solutions**

1. Change directory before and after the relevant dynamic import
2. Give dynamic datafiles some kind of input with the path to the project directory, like for instance as a parameter for function-based dynamic data files.

**Comment by bramceulemans** [comment]
This should be fairly easing using ```node
process.chdir(process.cwd());
```
